development:
  adapter: postgresql
  encoding: unicode
  database: lifestyle_articles
  pool: 5
  username: tashfeen
  password: gateway123

test:
  adapter: postgresql
  encoding: unicode
  database: lifestyle_articles_test
  pool: 5
  username: tashfeen
  password: gateway123